[package]
name = "connection_blocker"
version = "0.1.0"
authors = ["Sorridi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iptables = "0.2.2"
